#:schema node_modules/wrangler/config-schema.json
name = "spacetime-gateway"
main = "src/index.ts"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "router.spacetimee.xyz", zone_name = "spacetimee.xyz" },
  { pattern = "router.spacetimee.xyz/v1/*", zone_name = "spacetimee.xyz" }
]

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
head_sampling_rate = 1
persist = true

[triggers]
crons = ["*/5 * * * *"]

[vars]
# ===== Logging & Debug =====
DISABLE_LOGGER_OUTPUT = ""      # [flag] Disable request logging
