#:schema node_modules/wrangler/config-schema.json
name = "spacetime-gateway"
main = "src/index.ts"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "router.spacetimee.xyz/v1/*", zone_name = "spacetimee.xyz" }
]

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
head_sampling_rate = 1
persist = true

[vars]
# ===== Core Settings =====
CLERK_SECRET_KEY = ""           # [secret] Clerk secret key
ROUTER_API_KEY = ""             # [secret] Router API key

# ===== Logging & Debug =====
DISABLE_LOGGER_OUTPUT = ""      # [flag] Disable request logging
